---
- name: create vcl database
  action: command /usr/bin/mysqladmin create vcl
- name: create a vcl database user
  action: command /usr/bin/mysql -e "GRANT SELECT,INSERT,UPDATE,DELETE,CREATE TEMPORARY TABLES ON $vcldb.* TO '$vclusername'@'localhost' IDENTIFIED BY '$vcluserpassword'" 
- name: import vcl database
  action: shell /usr/bin/mysql --user=root vcl < /usr/share/doc/vcl-2.2.1/vcl.sql
- name: create an ssh keypair for vcl
  action: shell /usr/bin/ssh-keygen -q -t dsa -C '' -N '' -f /etc/vcl/vcl.key
- name: generate key.pem
  action: command /usr/bin/openssl genrsa -aes256 -passout pass:$pemkey -out /usr/share/vcl-web/.ht-inc/keys.pem 2048 
- name: generate pubkey.pem 
  action: command /usr/bin/openssl rsa -pubout -passin pass:$pemkey -in /usr/share/vcl-web/.ht-inc/keys.pem -out /usr/share/vcl-web/.ht-inc/pubkey.pem 
- name: setup /etc/hosts
  action: shell /bin/echo '${ansible_eth0.ipv4.address} $hostname.$domain' >> /etc/hosts
