---

- hosts: percona 
  user: root
  tasks:
   - include: ../roles/percona/tasks/common.yml

- hosts: percona[0]
  user: root
  tasks:
   - include: ../roles/percona/tasks/bootstrap.yml

- hosts: percona[1:2]
  user: root
  tasks:
  - include: ../roles/percona/tasks/start.yml

- hosts: percona[0]
  user: root
  tasks:
   - include: ../roles/percona/tasks/start.yml
